language: node_js

node_js:
  - "10"
  - "12"
  - "14"

# New docker container based test
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  # only place to find these files is maxmind php api repo
  - git clone https://github.com/maxmind/geoip-api-php.git database/php
  - cd database
  - ln -s php/tests/data/*.dat .

install:
  - yarn install --frozen-lockfile

script:
  - yarn test
