language: node_js

node_js:
  - "10"
  - "12"
  - "14"

#before_install:
#  - sudo rm -rf /dev/shm
#  - sudo ln -Tsf /{run,dev}/shm
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq wget gzip curl


# New docker container based test
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
